### ISSUE TITLE
Do you know about https://github.com/joke2k/faker ?

### ISSUE THREAD

**Issue by WarmongeR1** [deepthawtz/faker#18]
subj

**Comment by deepthawtz** [comment]
yeah, I just saw that yesterday after updating this project. I've been out of the Python loop for a while. 

I should probably retire this project and point folks to joke2k/faker

**Comment by deepthawtz** [comment]
Have contacted maintainers of the joke2k/faker package and am giving up the "faker" PyPi namespace to them. Added deprecation warnings to advise everyone to make the switch. After Sept 15, 2016 "faker" on PyPi will be joke2k/faker.
